---

name: Lint

on:
  push:
    branches: [latest, v*]
    paths:
      - '**.py'
      - '**.yml'
      - '.github/workflows/lint.yml'
      - 'requirements.txt'
      - 'requirements_test.txt'
  pull_request:
    branches: [latest, v*]
    paths:
      - '**.py'
      - '**.yml'
      - '.github/workflows/lint.yml'
      - 'requirements.txt'
      - 'requirements_test.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements_test.txt
        shell: bash

      - name: Running Yamllint
        run: yamllint .
        shell: bash

      - name: Running PyLint
        run: |
          cd lib/
          pylint --recursive=y .
        shell: bash
